### ISSUE TITLE
Bose driver discovery: possible bug

### ISSUE THREAD

**Issue by toddaustin07** [SmartThingsCommunity/SmartThingsEdgeDrivers#1061]
Line 99 of [discovery.lua ](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/beta/drivers/SmartThings/bose/src/disco.lua)
```
elseif err == "timeout" and socket ~= nil then
```
Should reference to 'socket' be 'sock'?  Even so, not sure it still makes sense...

**Comment by NoahCornell** [comment]
Hi @toddaustin07,

You are correct that this should be `sock` instead of `socket`. I went ahead and fixed it [here](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1067/commits/abe42cb21f24e1a36c409ef5a2d2df17f3f1fa8e). In this case, if `sock ~= nil` then we have already sent the ssdp discovery request and since the error is timeout we break out of the loop as we have likely received all the responses to the initial request.
