### ISSUE TITLE
zwave lock draining battery

### ISSUE THREAD

**Issue by rym002** [SmartThingsCommunity/SmartThingsEdgeDrivers#635]
Recently 1st or 2nd week of March my Kwikset lock battery drained. My battery is draining in about 24 hours. 
I tried to reset my zwave network with no luck. According to  [on-my-smartcode-the-batteries-drain-within-a-few-weeks](https://www.kwikset.com/support/answers/on-my-smartcode-the-batteries-drain-within-a-few-weeks) the issue could be a high polling interval. This commit added the refresh capability [3ff7ef7](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/commit/3ff7ef7bdf26f52a18a2da74b8938259ccbab4da).

Are there options to disable the refresh or lower the interval to avoid killing my batteries?

**Comment by dljsjr** [comment]
Hey @rym002! Thanks for the bug report. The addition of the refresh capability likely *isn't* the culprit as that should only get triggered if the device receives an explicit refresh command (e.g. you do a pull to refresh in the mobile app). In fact, it had that capability already, just in the defaults.

There are likely other configuration parameters that are causing over-polling that are causing battery drain and this is definitely on our radar now.

If our responses seem delayed or if bug fixes seem delayed, it's only because [we're still actively working on DTH -> Edge Driver migration](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/issues/642) so there are definitely still lots of bugs to be found and fixed :)

**Comment by rym002** [comment]
I have disabled all automatons and still getting battery drain. Not sure
how to solve this.
