### ISSUE TITLE
Is there a driver for zigbee vibration sensors? How can I add a vibration device to SmartThings？

### ISSUE THREAD

**Issue by 1joyce** [SmartThingsCommunity/SmartThingsEdgeDrivers#717]

**Comment by dljsjr** [comment]
Hi @1joyce! "Vibration Sensors" aren't really well defined in the Zigbee world. They exist but most of them work by providing post-processing over an acceleration sensor.

An example of an existing Zigbee device that provides a vibration notification on our platform is the Zigbee Contact Sensor's Multisensor profile: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zigbee-contact/profiles/multi-sensor.yml

Because we are very busy in the migration process of moving our legacy DTH integrations over to our new Edge Drivers platform, we'd like to keep this issue tracker limited to issues that are identifying bugs that have been found in the edge driver code, as per this pinned issue: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/issues/642

I would very much encourage you to re-open this question on the community forums, though, where you'll find that there are both very helpful power users as well as SmartThings developers available to guide you towards more information on integrating your sensor with our platform!
